name: gestion_presence_etudiant
description: Application mobile de gestion de prÃ©sence par reconnaissance faciale
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http_parser: ^4.0.2
  
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # State Management
  provider: ^6.1.2
  
  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3+1
  
  # Storage local
  shared_preferences: ^2.2.3
  
  # Camera & Image
  camera: ^0.10.6
  image_picker: ^1.1.1
  image: ^4.2.0
  
  # File handling
  file_picker: ^8.0.3
  path_provider: ^2.1.3
  path: ^1.9.0
  open_file: ^3.3.2
  
  # JWT Decoder
  jwt_decoder: ^2.0.1
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Date & Time
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true